### ISSUE TITLE
Race condition handling vs. transparency

### ISSUE THREAD

**Issue by johto** [bgentry/que-go#2]
Hi,

I think the handling of the race condition [here](https://github.com/bgentry/que-go/blob/affe9faf7ede469857554c867b9717ff827d6834/que.go#L236) is not optimal.  I couldn't decipher what the original Ruby module does here, but I think returning `nil, nil` is wrong, since that would give the caller the impression that there are no more items in the queue.  I think there's two options here:

  1) Return a special error to let the user know that it should retry the call to LockJob()
  2) Loop in LockJob() directly, until we know the queue is empty or we get a job without hitting the race

I think #2 is a significantly better an option.  Thoughts?  You want me to prepare a PR?

**Comment by bgentry** [comment]
@johto I like #2 as I don't think this detail should be exposed to outside users. The only concern that comes to mind is that you could in theory loop many times. That should be extremely unlikely given the rarity of that race condition, but I do think we should guard against looping infinitely. How do you think we should protect against that?

Please do create PR if you'd like. Thanks for your feedback so far!

**Comment by johto** [comment]
Fixed by #3
