### ISSUE TITLE
Is this project production ready?

### ISSUE THREAD

**Issue by mauricioklein** [bgentry/que-go#22]
Hello!

First of all, great job on porting `Que` for Go, really appreciate 😄 

I'm considering using this library in a production system, but haven't seen cases of real production usage. Also, I can't see any CI label on the README file or integration with code quality tools, so I'm just wondering if this is still an ongoing project or production ready.

In the later case, can someone share your thoughts and performance findings about the library?

Otherwise, I'll be more than happy to do some tests and benchmarks and share my findings.

Thanks in advance! 👍

**Comment by aeijdenberg** [comment]
Hi @mauricioklein - I can't speak in general for the project as I'm not a maintainer, but as a user for the past few months it's performed well for us and we haven't seen any issues (other than when trying to cleanly stop an app which is busy for which we've sent https://github.com/bgentry/que-go/pull/20 to fix).

From a project activity standpoint it's a little disheartening to not see any progress on that PR, particularly a simple one that fixes what I think is a clear bug - but on the other hand, maintainers are busy people, and with the way Go is managing vendored dependencies, it hasn't really bothered us to just put an override in our `Gopkg.toml` to use our fork instead which we'll keep in place until it's merged.

On the other hand, a lack of activity can also mean a really solid bit of code that does what says it says on the box smoothly, and thus no news is good news! :)

**Comment by mauricioklein** [comment]
Thanks a lot for your comment @aeijdenberg , really appreciated!

I totally agree: a low activity can also means a stable project, which is very good.

Until your PR isn't merged, is your personal fork public? If so, maybe make sense to use it for now.
Otherwise, I'll create my own.

In any case, thanks a lot for your support :+1:

**Comment by aeijdenberg** [comment]
Yes, our fork is public - we have the following in our `Gopkg.toml` file:

```toml
[[constraint]]
  name = "github.com/bgentry/que-go"
  source = "github.com/govau/que-go"
  branch = "fixshutdown"
```

(although I plan to delete our branch if/when #20 lands)
