### ISSUE TITLE
Are Job.Done() and Job.Delete() a public API?

### ISSUE THREAD

**Issue by Hixon10** [bgentry/que-go#26]
Hello,

I am little confusing. I read <a href="https://godoc.org/github.com/bgentry/que-go">documentation</a> and  see there:
```go
func (*Job) Delete 
func (*Job) Done 
func (*Job) Error 
```

Then I read the implementation of `WorkOne`:
```go
func (w *Worker) WorkOne() (didWork bool) {
	j, err := w.c.LockJob(w.Queue)
	if err != nil {
		log.Printf("attempting to lock job: %v", err)
		return
	}
	if j == nil {
		return // no job was available
	}
	defer j.Done()
	defer recoverPanic(j)

	didWork = true

	wf, ok := w.m[j.Type]
	if !ok {
		msg := fmt.Sprintf("unknown job type: %q", j.Type)
		log.Println(msg)
		if err = j.Error(msg); err != nil {
			log.Printf("attempting to save error on job %d: %v", j.ID, err)
		}
		return
	}

	if err = wf(j); err != nil {
		j.Error(err.Error())
		return
	}

	if err = j.Delete(); err != nil {
		log.Printf("attempting to delete job %d: %v", j.ID, err)
	}
	log.Printf("event=job_worked job_id=%d job_type=%s", j.ID, j.Type)
	return
}
```

So, I see, that library calls `j.Done()`, `j.Error(err.Error())` and `j.Delete()`. So, I cannot understand, are there functions public API? Or why there are these calls in `WorkOne()`.

**Comment by bgentry** [comment]
Yes, those are public APIs. However you should only need to use them manually if you aren't using a `Worker` and are instead using `Client` to manually lock jobs and work them yourself.
