### ISSUE TITLE
Is there any API for Periodic jobs?

### ISSUE THREAD

**Issue by Hixon10** [bgentry/que-go#27]
Hello,

Is there any API for Periodic jobs?

If not, what do you think about this? Should I implement it and create PR? Or, do you think, that this is not a necessary feature?

**Comment by bgentry** [comment]
Hi @Hixon10, I recommend you check out my new project, [River](https://github.com/riverqueue/river). River already does quite a bit more than que-go (including periodic jobs), uses a much more scalable design, and is designed for modern Go and pgx/v5.

I will be archiving this repository shortly.
