### ISSUE TITLE
Allow using multiple drivers

### ISSUE THREAD

**Issue by gadelkareem** [bgentry/que-go#35]
How hard would it be to implement a driver interface where you can connect to different backend such as redis, rabbitMQ,..etc? Or if there is already a plan for that?

**Comment by bgentry** [comment]
No, that wouldn't really make sense for this project. It was built as a port of the Que library in Ruby, which makes heavy use of PostgreSQL-specific features. Really the entire purpose of it is to have a queue which is transactional with your Postgres database.
