### ISSUE TITLE
Job Updates

### ISSUE THREAD

**Issue by grippy** [bgentry/que-go#37]
Just started using this package and I have a use-case that isn't currently covered. 

The existing code assumes all successful jobs returned from a handler should be deleted. However, I would like to modify the job (eta, priority, etc) and have it updated in the DB. [See code here](https://github.com/bgentry/que-go/blob/master/worker.go#L120-L127).

The change looks straight-forward:

- Add a new struct `Job` flag which tells the worker how to proceed with the Job. The default behavior should delete the job for backwards compatibility.

I'm more than willing to work on a PR for this functionality. Just wanted to run this by you before doing any work.

Thanks!

**Comment by grippy** [comment]
This feature was added to this fork: https://github.com/gadelkareem/que/pull/1

**Comment by bgentry** [comment]
Hi @grippy, I recommend you check out my new project, [River](https://github.com/riverqueue/river). River already does quite a bit more than que-go, uses a much more scalable design, and is designed for modern Go and pgx/v5.

I will be archiving this repository shortly.
