### ISSUE TITLE
Opening this project to the community

### ISSUE THREAD

**Issue by marccarre** [bgentry/que-go#41]
First and foremost: thank you so much for this awesome project @bgentry! 🙇🏻 
Given it seems this project is no longer maintained, and given its usefulness to many, my ask to you would be to open it to the community. 🙏🏻 

1. It would avoid the bazillion forks all re-implementing the same in slightly different ways.
2. It would allow developers stumbling upon this project to more easily make use of it.
3. It would carry on your legacy. 🙂 

My suggestion would be to invite people who already forked this project, created issues, or opened PRs.
This could be done either to this project as-is, or by transferring this project to a different GitHub organisation, for more convenient management of this project (e.g. `github.com/que-go/que-go`).

Thoughts?

**Comment by bgentry** [comment]
Hi, I'm not opposed to this in principle, but it's challenging to vet a new owner if it's not somebody I have a history with.

Perhaps a better option would be to just create that new org/fork? I'd be happy to post a notice on this project to direct others to go there instead. My repo here isn't at all up-to-date with modern Go, nor is it the most efficient system design these days.

As long as the copyright is maintained I have no issues with this.

**Comment by marccarre** [comment]
Thank you for your reply. This is very good to hear.

A new org/fork sounds good to me 👍🏻 .
I wish I could say I'll drive this, but I lack the bandwidth myself, and can probably only help in an ad-hoc fashion once in a while. Maybe someone reading this will be keen to get involved though. 🙂 🤞🏻

**Comment by bgentry** [comment]
Hi everyone,  I recommend you check out my new project, [River](https://github.com/riverqueue/river). River already does quite a bit more than que-go, uses a much more scalable design, and is designed for modern Go and pgx/v5. If you've been getting any value out of que-go or any of its descendents, I think you'll really like River.

I will be archiving this repository shortly.
