### ISSUE TITLE
Support job max retries

### ISSUE THREAD

**Issue by anh** [bgentry/que-go#6]
there is no way to stop retrying job after `job.ErrorCount > max_retries_allowed`. I was thinking of adding `MaxRetries` to Job however it means some of the job queries must be updated. Is it good practice to add MaxRetries attribute to `Worker` type and `WorkerPool` instead and then checking the retrying inside `WorkOne()`?

```
if err = wf(j); err != nil {
        if j.ErrorCount > int32(w.MaxRetries) {
            if err = j.Delete(); err != nil {
                log.Printf("attempting to delete job %d: %v", j.ID, err)
            }
        } else {
            j.Error(err.Error())
        }
        return
    }
```

**Comment by bgentry** [comment]
Have you taken a look at what the Ruby Que library does here? My goal is to
stay as close to that as possible, and maybe they already have a solution
for max retries.

**Comment by anh** [comment]
Thank you for reminding me about Ruby Que library, I have a look at it and find a section on [Not retrying certain failed jobs](https://github.com/chanks/que/blob/master/docs/customizing_que.md#not-retrying-certain-failed-jobs) . As I understand it customizes Que::Job with SkipRetries which deletes failed job when errors occur then reraise.  I'll study more to see how to adapt it to que-go.

**Comment by hazcod** [comment]
What can be done here @bgentry to prevent a task from looping?
