### ISSUE TITLE
 relation "que_jobs" does not exist 

### ISSUE THREAD

**Issue by gernest** [bgentry/que-go#7]
Hello, I have followed the example setup but whenever I start my application I get this erro

```bash
 ERROR: relation "que_jobs" does not exist (SQLSTATE 42P01
```

Am I missing something or?

**Comment by bgentry** [comment]
Surprised I haven't caught this yet :)

There's a file schema.sql which contains the schema you'd need to run to
create that table. I'll need to add this to the docs too.

**Comment by gernest** [comment]
@bgentry thanks, let me check this file out.

That will be nice to add it to the docs. Nice work .

**Comment by gernest** [comment]
@bgentry After ezecuting `schema.sql` everything is fine now.
