### ISSUE TITLE
Is there any proper way to use query builder (such as dbr) in Job?

### ISSUE THREAD

**Issue by achiku** [bgentry/que-go#8]
@bgentry Hi, this is really nice work!

Is there any proper manner to use other query builders in Job? When it comes to dynamically changing condition, query builder is really useful, and it would be nice if you can point me where to look at.

I'm currently using [dbr](https://github.com/gocraft/dbr) for query builder, and thinking to wrap `pgx.Tx` in `dbr.TX`.

**Comment by bgentry** [comment]
@achiku it looks like dbr wouldn't be compatible because in addition to building queries, it's also taking over the process of making connections to the database using `database/sql` under the hood.
